title: Page

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  textarea

  class:
    label: Body class
    type: text

  SEOtitle:
    label: SEO Title
    type: text
    width: 1/2
    
  SEOdescription:
    label: SEO Description
    type: text
    width: 1/2